export const CATEGORIES: any = [
  { name: 'Food & Dining' },
  { name: 'Groceries' },
  { name: 'Transportation' },
  { name: 'Entertainment' },
  { name: 'Health & Wellness' },
  { name: 'Shopping' },
  { name: 'Utilities' },
  { name: 'Rent' },
  { name: 'Travel' },
  { name: 'Education' },
  { name: 'Subscriptions' },
  { name: 'Gifts & Donations' },
  { name: 'Insurance' },
  { name: 'Personal Care' },
  { name: 'Other' },
  { name: 'Income' },
  { name: 'Credit Card Payment' },
  { name: 'Transfer' },
];
